### PR TITLE
Separate check into SpamEmail.blacklisted? method

### PR DESCRIPTION
**Pull request by korny**
This allows us to use the blacklist more flexibly, instead of just as a Rails validation.

### CODE REVIEW

**Comment by korny** [comment]
Sorry, it includes lots of new blacklist entries from @colin now, too. Should we put the changes into separate pull requests?

**Comment by phillipp** [comment]
Hey, very nice to see some activity on the project, I love it!

I'm pretty busy right now and I don't think I can be of much assistance at the moment. I gave you rights on the repo so you can merge/edit/commit as you see fit. The gem has no black magic in it so everything should be pretty straight forward.

Just give me a holla if you want a new gem version uploaded ;-)

**Comment by korny** [comment]
Cool! :+1: We're actively using it to fight a situation at sofatutor right now, so after we tested it enough in production, I will suggest a new release.

**Comment by phillipp** [comment]
Cool, I like that it's useful to you! If you need anything else just say so.

**Pull request merged**
